FROM ubuntu:16.04

MAINTAINER piotr - dot - justyna - at - gmail.com

# Install dependencies.
RUN apt-get update && \
    apt-get install --assume-yes curl gcc libgmp-dev make xz-utils zlib1g-dev

# Install Stack.
RUN curl --location https://www.stackage.org/stack/linux-x86_64-static > stack.tar.gz && \
  tar xf stack.tar.gz && \
  cp stack-*-linux-x86_64-static/stack /usr/local/bin/stack && \
  rm -f -r stack.tar.gz stack-*-linux-x86_64-static/stack && \
  stack --version

# Install GHC.
WORKDIR /haskell-warp
COPY haskell-warp/stack.yaml /haskell-warp
RUN stack setup && stack exec -- ghc --version

# Build.
COPY /haskell-warp /haskell-warp
RUN stack build --copy-bins --local-bin-path /usr/local/bin

# Run project.
ENV HOST 0.0.0.0
ENV PORT 3000
EXPOSE 3000
CMD /usr/local/bin/haskell-warp-exe